#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 27 17:33:44 2022

@author: cxiong
"""

import matplotlib.pyplot as plt
import numpy as np



x = [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1]

y = [0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62]


plt.plot(x, y, 'r*-', label='ax1', linewidth=2)
plt.title('learning rate effect')
plt.xlabel("learning rate")
plt.ylabel("f1 score")

plt.ylim(0,1)
plt.grid()
plt.show()

